**MINI** **PROJECT**








Loading The Data

In [27]:
#Load the numpy
import numpy as np
import pandas as pd
#Uploading the path of file 
data_file="/content/makeSenseOfCensus.csv"
#defining the file as a numpy array
data=np.genfromtxt(data_file,delimiter=',',skip_header=1,names=True)

data=pd.read_csv("/content/makeSenseOfCensus.csv")
print("\nData: \n\n",data)


Data: 

      age  education-num  race  ...  capital-loss  hours-per-week  income
0     39             13     4  ...             0              40       0
1     50             13     4  ...             0              13       0
2     38              9     4  ...             0              40       0
3     53              7     2  ...             0              40       0
4     28             13     2  ...             0              40       0
..   ...            ...   ...  ...           ...             ...     ...
995   56              9     4  ...             0              55       1
996   45             14     4  ...             0              45       0
997   48             13     4  ...             0              58       1
998   40             10     4  ...             0              40       0
999   39             13     4  ...             0              50       1

[1000 rows x 8 columns]


Printing The Type of Data

In [28]:
print("\nType of Data: \n\n",type(data))


Type of Data: 

 <class 'pandas.core.frame.DataFrame'>



# Step 2 : Append the Data
Append 'new_record' (given) to 'data' using "np.concatenate()"¶

In [29]:
new_record =np.array([[50,9,4,1,0,0,40,0]])
data=np.concatenate((data,new_record),axis=0)

# Step 3 : Check if it's a young country or old country

Q-1  ::
Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array

In [30]:
#creating an array with age Column
age=data[:,0]
#printing the Array
print(age)

[39 50 38 ... 40 39 50]


Q-2::
Find the max age and store it in a variable called 'max_age'.

In [31]:
max_age=age.max()
print(max_age)

90


Q-3: Find the min age and store it in a variable called 'min_age'

In [32]:
min_age=age.min()
print(min_age)

17


Q-4::Find the mean of the age and store it in a variable called 'age_mean'



In [33]:
age_mean=(age.sum()/age.size)
print(age_mean)

38.06293706293706


Q-5:Find the standard deviation of the age and store it in a variable called 'age_std'

In [34]:
age_std=np.std(age)
print(age_std)

13.341478176165857


# Step 4: Let's check the country's race distribution to identify the minorities

In [35]:
race=data[:,2]
race.shape

(1001,)

Q-1: Create five different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

In [36]:
#Creating Array with Race 0
race_0=data[data[:,2]==0]
print(race_0)

[[34  4  0  1  0  0 45  0]
 [35 10  0  0  0  0 40  0]
 [60  6  0  0  0  0 10  0]
 [51  9  0  1  0  0 40  0]
 [25 10  0  0  0  0 20  0]
 [20  9  0  1  0  0 48  0]
 [23 10  0  0  0  0 25  0]
 [29  9  0  1  0  0 40  0]
 [27 12  0  1  0  0 40  0]
 [31 12  0  0  0  0 40  0]]


In [37]:
#Creating Array with Race 1
race_1=data[data[:,2]==1]
print(race_1)

[[  30   13    1    1    0    0   40    1]
 [  40   11    1    1    0    0   40    1]
 [  54   10    1    1    0    0   60    1]
 [  30    9    1    0    0 1573   35    0]
 [  49   10    1    1    0    0   40    1]
 [  33   13    1    0    0    0   40    0]
 [  44   14    1    0    0    0   40    0]
 [  28    9    1    0    0    0   40    0]
 [  60    9    1    1    0    0   40    0]
 [  42    9    1    1    0    0   40    1]
 [  37   10    1    1    0    0   75    1]
 [  39   14    1    0 3464    0   40    0]
 [  21   10    1    0    0    0   25    0]
 [  24   10    1    0    0    0   40    0]
 [  34   14    1    1 7298    0   35    1]
 [  27   10    1    1    0 1980   40    0]
 [  40   11    1    1    0    0   40    1]
 [  55    9    1    0    0    0   40    0]
 [  35   16    1    1    0    0   40    1]
 [  29   10    1    0    0    0   40    0]
 [  20    7    1    0    0 1762   40    0]
 [  55   10    1    0    0    0   40    0]
 [  51   13    1    1    0 2415   40    1]
 [  28   11

In [38]:
#creating Array With Race 2
race_2=data[data[:,2]==2]
print(race_2)

[[  53    7    2    1    0    0   40    0]
 [  28   13    2    0    0    0   40    0]
 [  49    5    2    0    0    0   16    0]
 [  37   10    2    1    0    0   80    1]
 [  32   12    2    1    0    0   50    0]
 [  54    9    2    0    0    0   20    0]
 [  35    5    2    1    0    0   40    0]
 [  20   10    2    1    0    0   44    0]
 [  22   10    2    1    0    0   15    0]
 [  57   13    2    1    0    0   40    1]
 [  31   13    2    0    0    0   40    0]
 [  28   10    2    0    0    0   25    0]
 [  32    9    2    1    0    0   40    0]
 [  49   11    2    1    0    0   40    1]
 [  30   13    2    1    0    0   40    0]
 [  19   10    2    1    0    0   35    0]
 [  46   12    2    0    0    0   36    0]
 [  31    9    2    0    0    0   30    0]
 [  71   10    2    1    0 1816    2    0]
 [  42   13    2    1    0    0   50    0]
 [  21    9    2    1    0    0   40    0]
 [  34    9    2    1    0    0   40    0]
 [  44   10    2    1    0    0   38    1]
 [  30   10

In [39]:
#creating Array with Race 3
race_3=data[data[:,2]==3]
print(race_3)

[[  25   10    3    0    0    0   40    0]
 [  33   10    3    0    0    0   40    0]
 [  65    7    3    1    0    0   40    0]
 [  28    4    3    1    0 2179   40    0]
 [  44    7    3    0    0    0   46    0]
 [  40   13    3    0    0    0   55    1]]


In [40]:
#creating Array With Race 4
race_4=data[data[:,2]==4]
print(race_4)

[[39 13  4 ...  0 40  0]
 [50 13  4 ...  0 13  0]
 [38  9  4 ...  0 40  0]
 ...
 [40 10  4 ...  0 40  0]
 [39 13  4 ...  0 50  1]
 [50  9  4 ...  0 40  0]]


Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

In [41]:
#checking the Length of Race_0 Array and Printing It
len_0=len(race_0)
print("Length of Race_0:",len_0)
#checking the Length of Race_1 Array and Printing It
len_1=len(race_1)
print("Length of Race_1:",len_1)
#checking the Length of Race_2 Array and Printing It
len_2=len(race_2)
print("Length of Race_2:",len_2)
#checking the Length of Race_3 Array and Printing It
len_3=len(race_3)
print("Length of Race_3:",len_3)
#checking the Length of Race_4 Array and Printing It
len_4=len(race_4)
print("Length of Race_4:",len_4)

Length of Race_0: 10
Length of Race_1: 27
Length of Race_2: 110
Length of Race_3: 6
Length of Race_4: 848


Q-3: Find out which is the race with the minimum no. of citizens

In [47]:
#Check the Minium Length of Of All these Arrays
min_citizen=min(len_0,len_1,len_2,len_3,len_4)
if min_citizen==len_0:
  print("{} has Minimum Citizen= {}".format('race_0',len_0))
elif min_citizen==len_1:
  print("{} has Minimum Citizen= {}".format('race_1',len_1))
elif min_citizen==len_2:
  print("{} has Minimum Citizen= {}".format('race_2',len_2))
elif min_citizen==len_3:
  print("{} has Minimum Citizen= {}".format('race_3',len_3))
elif min_citizen==len_4:
  print("{} has Minimum Citizen= {}".format('race_4',len_4))
else:
  pass

race_3 has Minimum Citizen= 6


Q:4-Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [51]:
if min_citizen==len_0:
  minority_race=0
  print("Minority Race:",minority_race)
elif min_citizen==len_1:
  minority_race=1
  print("Minority Race:",minority_race)
elif min_citizen==len_2:
  minority_race=2
  print("Minority Race:",minority_race)
elif min_citizen==len_3:
  minority_race=3
  print("Minority Race:",minority_race)
elif min_citizen==len_4:
  minority_race=4
  print("Minority Race:",minority_race)
else:
  pass

Minority Race: 3


# Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

Q:1-Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

In [56]:
#creating a New Subset Array in which all details of  Citizen's >60 is stored
senior_citizen=data[data[:,0]>60]
print(senior_citizen)

[[   79    10     4     1     0     0    20     0]
 [   67     6     4     1     0     0     2     0]
 [   76    14     4     1     0     0    40     1]
 [   61     9     4     1     0     0    40     0]
 [   70    10     4     1     0     0    40     0]
 [   64     7     4     1     0  2179    40     0]
 [   71    10     2     1     0  1816     2     0]
 [   68     2     4     0     0     0    20     0]
 [   66    11     4     0     0     0    20     0]
 [   64     2     4     1     0     0    40     0]
 [   90     9     2     1     0  2206    40     0]
 [   66     9     4     1  1409     0    50     0]
 [   75    11     4     0     0     0    20     0]
 [   65     9     4     0     0     0    40     0]
 [   64     9     4     1     0     0    40     1]
 [   61     9     4     1     0     0    40     1]
 [   65     9     4     1     0     0    16     0]
 [   77    10     4     1     0     0    40     0]
 [   62     9     4     0     0     0    24     0]
 [   76    14     4     1     0

Q-2 : Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

In [57]:
working_hours_sum=sum(senior_citizen[:,6])
print(working_hours_sum)

1917


Q-3: Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

In [60]:
senior_citizen_len=len(senior_citizen)
print("Total No. of Citizen With Age Greater then 60 is = ",senior_citizen_len)

Total No. of Citizen With Age Greater then 60 is =  61


Q-4: Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

In [61]:
avg_working_hours=working_hours_sum/senior_citizen_len


31.42622950819672


Q-5: Print 'avg_working_hours' and see if the govt. policy is followed.

In [63]:
print("Average Working Hours is= ",round(avg_working_hours,2))
if (avg_working_hours<25):
  Print("Govt Policy is Followed")
else:
  print("Govt Policy is Not Followed")

Average Working Hours is=  31.43
Govt Policy is Not Followed


# Step 6: Let's check that higher educated people have better pay in general.

Q-1: Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.

In [64]:
high=data[data[:,1]>10]
low=data[data[:,1]<=10]
print("high: ",high)
print("low: ",low)

High:  [[39 13  4 ...  0 40  0]
 [50 13  4 ...  0 13  0]
 [28 13  2 ...  0 40  0]
 ...
 [45 14  4 ...  0 45  0]
 [48 13  4 ...  0 58  1]
 [39 13  4 ...  0 50  1]]
low:  [[38  9  4 ...  0 40  0]
 [53  7  2 ...  0 40  0]
 [49  5  2 ...  0 16  0]
 ...
 [56  9  4 ...  0 55  1]
 [40 10  4 ...  0 40  0]
 [50  9  4 ...  0 40  0]]


Q-2: Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

In [65]:
#Calculating The Avg pay for High Educated People 
sum_of_high=sum(high[:,7])
len_of_high=len(high[:,7])
avg_pay_high=sum_of_high/len_of_high
print("Average Pay of Higher Educated People is ",avg_pay_high)


Average Pay of Higher Educated People is  0.42813455657492355


In [66]:
#Calculating The Avg Pay for Low Educated People
sum_of_low=sum(low[:,7])
len_of_low=len(low[:,7])
avg_pay_low=sum_of_low/len_of_low
print("Average Pay of Low Educated People is ",avg_pay_low)

Average Pay of Low Educated People is  0.13649851632047477
